FROM alpine:latest

ENV ROOT_PASSWORD=ChangeMe!

EXPOSE 22

RUN 
apk update && apk upgrade \
           && apk add --no-cache openssh \
           && sed -i s/#PermitRootLogin./PermitRootLogin\ yes/ /etc/ssh/sshd_config \
           && echo "root:${ROOT_PASSWORD}" | chpasswd \
           && rm -rf /var/cache/apk/ /tmp/*

COPY entrypoint.sh /usr/local/bin/

ENTRYPOINT [entrypoint.sh]